window.__ModuleLoader__.load({ id: "dsh-kimi-code-oauth", factory: (require) => {
  const react = require("react"); const NS = "dsh-kimi-code-oauth";
  const zh = { nav:"Kimi Code", title:"Kimi Code 订阅", description:"使用 Kimi Code 订阅登录。", login:"登录 Kimi Code", logout:"退出登录", signedIn:"已登录", signedOut:"未登录", loading:"加载中…", open:"打开授权页", code:"设备码", refresh:"刷新状态", error:"登录失败", models:"模型", save:"保存模型" };
  const en = { nav:"Kimi Code", title:"Kimi Code subscription", description:"Sign in with your Kimi Code subscription.", login:"Sign in to Kimi Code", logout:"Sign out", signedIn:"Signed in", signedOut:"Signed out", loading:"Loading…", open:"Open authorization page", code:"Device code", refresh:"Refresh status", error:"Sign-in failed", models:"Models", save:"Save models" };
  const paths={status:"/plugins/dsh-kimi-code/oauth/status",login:"/plugins/dsh-kimi-code/oauth/login",cancel:"/plugins/dsh-kimi-code/oauth/login-cancel",logout:"/plugins/dsh-kimi-code/oauth/logout",models:"/plugins/dsh-kimi-code/oauth/models"};
  async function api(path, options={}) { const response=await fetch(path,{...options,headers:{"content-type":"application/json",...(options.headers||{})}}); const value=await response.json(); if(!response.ok) throw new Error(value.error||response.statusText); return value; }
  function css(){if(document.getElementById("dsh-kimi-code-oauth-style"))return;const s=document.createElement("style");s.id="dsh-kimi-code-oauth-style";s.textContent=".dsh-kimi-page{color:var(--dsw-alias-label-primary,#1f2328);background:var(--dsw-alias-bg-layer-2,#fff);padding:16px;border:1px solid var(--dsw-alias-border-l2,#e5e7eb);border-radius:8px;display:flex;flex-direction:column;gap:12px}.dsh-kimi-page small{color:var(--dsw-alias-label-tertiary,#8b93a1)}.dsh-kimi-page button{width:max-content;color:var(--dsw-alias-label-primary,#1f2328);background:var(--dsw-alias-bg-layer-1,#fff);border:1px solid var(--dsw-alias-border-l2,#d1d5db);border-radius:6px;padding:7px 12px;cursor:pointer}.dsh-kimi-code{font:600 20px monospace;letter-spacing:2px;padding:8px;background:var(--dsw-alias-bg-layer-3,#f3f4f6);width:max-content}";document.head.appendChild(s)}
  function apply(ctx){css();ctx.effect(()=>ctx.locale.register(NS,{zh,en}),"dsh-kimi-code-oauth: dictionaries");const t=ctx.locale.bind(NS);ctx.slots.inject("settings.section",()=>ctx.slots.register({name:"settings.section",id:NS,order:45,label:()=>t("nav"),locale:NS,inject:()=>({t})},()=>{const [state,setState]=react.useState();const [busy,setBusy]=react.useState(false);const [selected,setSelected]=react.useState([]);const refresh=()=>api(paths.status).then(v=>{setState(v);setSelected(v.selected||v.models?.map(m=>m.id)||[])}).catch(e=>setState({error:e.message}));react.useEffect(()=>{refresh();const id=setInterval(refresh,2000);return()=>clearInterval(id)},[]);const run=async action=>{setBusy(true);try{await action();await refresh()}catch(e){setState(v=>({...v,error:e.message}))}finally{setBusy(false)}};return react.createElement("div",{className:"dsh-kimi-page"},react.createElement("strong",null,t("title")),react.createElement("span",null,t("description")),state?.error?react.createElement("span",{role:"alert"},`${t("error")}: ${state.error}`):null,state?.authenticated?react.createElement("span",null,t("signedIn")):react.createElement("span",null,t("signedOut")),state?.challenge?react.createElement(react.Fragment,null,react.createElement("a",{href:state.challenge.url,target:"_blank",rel:"noreferrer"},t("open")),state.challenge.userCode?react.createElement("span",null,t("code"),react.createElement("div",{className:"dsh-kimi-code"},state.challenge.userCode)):null):null,!state?.authenticated&&!state?.signingIn?react.createElement("button",{disabled:busy,onClick:()=>run(()=>api(paths.login,{method:"POST",body:"{}"}))},t("login")):null,state?.signingIn?react.createElement("button",{disabled:busy,onClick:()=>run(()=>api(paths.cancel,{method:"POST",body:"{}"}))},t("logout")):null,state?.authenticated?react.createElement("button",{disabled:busy,onClick:()=>run(()=>api(paths.logout,{method:"POST",body:"{}"}))},t("logout")):null,state?.authenticated?react.createElement("fieldset",null,react.createElement("legend",null,t("models")),state.models?.map(m=>react.createElement("label",{key:m.id,style:{display:"block"}},react.createElement("input",{type:"checkbox",checked:selected.includes(m.id),onChange:e=>setSelected(v=>e.target.checked?[...v,m.id]:v.filter(id=>id!==m.id))}),m.name||m.id)),react.createElement("button",{disabled:busy,onClick:()=>run(()=>api(paths.models,{method:"POST",body:JSON.stringify({selected,selectionMode:"selected"})}))},t("save"))):null,react.createElement("button",{disabled:busy,onClick:refresh},t("refresh")))}));}
  return {name:"dsh-kimi-code-oauth",inject:["slots","locale","theme"],apply};
}});
